[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'src/test'

solc_version = '0.8.15'
auto_detect_solc = false
optimizer = true
optimizer_runs = 1_000
ffi=true

fs_permissions = [{ access = "read", path = "./"}]

# See more config options https://github.com/gakonst/foundry/tree/master/config